### ISSUE TITLE
DatabaseURL doesn't use default value

### ISSUE THREAD

**Issue by jimfmunro** [jezdez/django-configurations#104]
I think this is new in Django 1.8. Using rc1. and latest master of configurations.

If I specify a default url like 

```DATABASES = values.DatabaseURLValue('postgres://myuser@localhost/mydb')```

I get a database error:

```
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
```
If I specify DATABASE_URL environment variable to the same url string, it works fine.

**Comment by marco-santamaria** [comment]
Same problem for me with Django 1.8 and commit 41dfcee46c550d01673d1d3fcba898e49d459852

**Comment by multivoxmuse** [comment]
I have the same issue. Using django 1.8.1, django-pyodbc-azure 1.8.1, pyodbc 3.0.10.

Trying to run tests without databases. I'm doing this by subclassing DiscoverRunner and overriding setup_databases() and teardown_databases() to just "pass", so that it does not create or teardown db when running tests.

This worked in django 1.6, and hasn't worked in django 1.7 +. One of the bugs I ran into in django 1.7.5 was [fixed in django 1.8c1](https://github.com/django/django/commit/e953c78eeb81ee69dccd356145563fd6f9e4c7b6), however now I'm running into this. Would appreciate any help.

**Comment by jezdez** [comment]
This will work in the next version.

**Comment by jimfmunro** [comment]
@jezdez sorry for the delayed kudos, but thanks for fixing! :)
