### ISSUE TITLE
Configs instantiated or verified regardless of whether used or not

### ISSUE THREAD

**Issue by AndySun25** [jezdez/django-configurations#86]
Forgive me for anything foolish I may write, I am still fairly new to both Python and Django.
I am currently attempting to rewrite a set of Django configs using django-configurations. The old config setup used imports between a common python module and dedicated modules i.e. local, production, debug etc.

At the moment the I have gotten the configurations to run properly but when I added a new production configuration which requires certain os environmental variables not present on development machines I am no longer able to run the Django server. An example here

    class common(Configuration):
        ...

    class local(common):
        ...

    class production(common):
        SOME_VARIABLE = os.environ['...']

In this case I have DJANGO_CONFIGURATION set to 'local' but for some reason django is still giving me a KeyError on the production config, even though it is not being used. Is this intended behavior or have I perhaps missed something?

**Comment by jezdez** [comment]
That doesn't have anything to do with django-configurations but is the usual Python behavior, any attribute on the class level is evaluated as soon as the module is loaded in which the class is contained in. Since `os.environ` is a dict-like variable it'll raise a `KeyError` when it can't find the item you ask it to. 

The solution for this problem is using the alternative `get` method of dict-like variables that doesn't raise an exception and allows you to define an optional default as well:

    class common(Configuration):
        ...

    class local(common):
        ...

    class production(common):
        SOME_VARIABLE = os.environ.get('SOME_ENV_VARIABLE', 'fallback value')

**Comment by AndySun25** [comment]
Thanks for the response!
